import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { connect, useDispatch } from 'react-redux'
import { useEffect, useState } from 'react'
import { useRouter } from "next/dist/client/router";
import { useSelector } from 'react-redux'
import ProductListPage from '../components/Products/index'
import CatList from '../components/catgegory/cat'
import { getCategoryStart, getShopProductsStart, getCategoryProductsStart, getSearchProductsStart } from "../redux/shop/shop-action";
const Home = ({ products, shop, categories, getCategoryStart, getCategoryProducts, getShopProducts }) => {

  const storeId = process.env.NEXT_PUBLIC_DEFAULT_STORE_ID;
  const Router = useRouter();
  const { category, subCategory, p } = Router.query;
  const [status, setStatus] = useState('loading') //status == loading || failed || success


  useEffect(() => { // Componentdidmount
    if (!categories.length) getCategoryStart(storeId);
    // setStatus('loading')

  }, [])

  useEffect(() => {
    if (category) {
      getCategoryProducts({ storeId, categoryId: category, subCategoryId: subCategory, page: p, setStatus })
      // setq('') // Cleaning query string of search
    }
    else {
      getShopProducts({ storeId, setStatus })
      setStatus('loading') // Set to success default Because its run whene All  products are fetching
      // setq('') // Cleaning query string of search
    }
  }, [Router.query])
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar /> */}
      <section>
        <div className='wrapper mx-auto'>
          <div className="grid grid-cols-11">
            <div className="col-span-2 border-r-2  border-gray-300 ">
              <CatList list={categories.length > 0 && categories} />
            </div>
            <div className="col-span-6  ">
              <ProductListPage products={products} />
            </div>
            <div className="col-span-2">03</div>
          </div>
        </div >
      </section >
    </div >
  )
}
const mapStateToProps = state => ({
  shop: state.store.shop,
  products: state.store.products,
  categories: state.store.categories,
})
const mapDispatchToProps = dispatch => ({
  getShopProducts: (storeId) => dispatch(getShopProductsStart(storeId)),
  getCategoryProducts: (data) => dispatch(getCategoryProductsStart(data)),
  getCategoryStart: (storeId) => dispatch(getCategoryStart(storeId)),

})
export default connect(mapStateToProps, mapDispatchToProps)((Home))

